# Generated by Django 5.2.11 on 2026-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_niat_campus_fk_and_shared_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='foundingeditorprofile',
            new_name='profiles_fo_campus__fbfadd_idx',
            old_name='profiles_fo_campus_8a2c91_idx',
        ),
        migrations.RenameIndex(
            model_name='foundingeditorprofile',
            new_name='profiles_fo_badge_a_04d531_idx',
            old_name='profiles_fo_badge_a_3f7e02_idx',
        ),
        migrations.RenameIndex(
            model_name='niatstudentprofile',
            new_name='profiles_ni_campus__0f5ada_idx',
            old_name='profiles_ni_campus_6e4b1b_idx',
        ),
        migrations.AlterField(
            model_name='foundingeditorprofile',
            name='campus_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
