# Generated by Django 6.0.2 on 2026-02-10 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for the senior profile.', primary_key=True, serialize=False)),
                ('proof_summary', models.TextField(blank=True, help_text='Summary or link to proof of NIAT senior status.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User requesting senior verification.', on_delete=django.db.models.deletion.CASCADE, related_name='senior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senior profile',
                'verbose_name_plural': 'Senior profiles',
                'db_table': 'verification_senior_profile',
                'indexes': [models.Index(fields=['status'], name='verificatio_status_0e0722_idx'), models.Index(fields=['created_at'], name='verificatio_created_648d7d_idx')],
            },
        ),
    ]
