# Generated by Django 6.0.2 on 2026-02-10 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Mobile number (e.g. E.164) being verified.', max_length=20)),
                ('otp_code', models.CharField(help_text='OTP sent to phone (hash in production).', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='OTP valid until this time.')),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, help_text='Set when user successfully submits correct OTP.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User claiming this phone; set when logged-in user requests verification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone verification',
                'verbose_name_plural': 'Phone verifications',
                'db_table': 'verification_phone_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'expires_at'], name='verificatio_phone_n_2f53f8_idx')],
            },
        ),
    ]
