# Generated by Django 5.2.11 on 2026-02-12 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_phoneverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name', max_length=255)),
                ('call_name', models.CharField(help_text='Preferred name or nickname', max_length=100)),
                ('college_email', models.EmailField(db_index=True, help_text='College email address', max_length=254)),
                ('personal_email', models.EmailField(help_text='Personal email for notifications', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('partner_college', models.CharField(help_text='Partner college name', max_length=100)),
                ('graduation_year', models.CharField(help_text='Expected graduation year', max_length=4)),
                ('branch', models.CharField(help_text='Branch/Department', max_length=100)),
                ('student_id', models.CharField(help_text='Student ID number', max_length=50)),
                ('current_status', models.CharField(help_text='Current status (Student/Intern)', max_length=50)),
                ('id_card_image', models.ImageField(help_text='College ID card image', upload_to='senior_registrations/id_cards/')),
                ('why_join', models.TextField(help_text='Why they want to join as a mentor')),
                ('best_experience', models.TextField(help_text='Best experience at NIAT')),
                ('advice_to_juniors', models.TextField(help_text='Advice for junior students')),
                ('skills_gained', models.TextField(help_text='Key skills gained')),
                ('college_email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_registrations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User account created/linked after approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senior Registration',
                'verbose_name_plural': 'Senior Registrations',
                'db_table': 'verification_senior_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='verificatio_status_402812_idx'), models.Index(fields=['college_email'], name='verificatio_college_868b2e_idx')],
            },
        ),
    ]
