# Generated by Django 5.2.11 on 2026-02-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_senior_onboarding_and_magic_login'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magiclogintoken',
            new_name='verificatio_token_4a3528_idx',
            old_name='verification_token_is_us_expires_idx',
        ),
    ]
