# Generated by Django 5.2.11 on 2026-02-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_senior_follow_follower_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seniorfollow',
            new_name='verificatio_senior__b88b38_idx',
            old_name='verificatio_senior__idx',
        ),
    ]
