# Generated by Django 6.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_id", models.CharField(db_index=True, max_length=36)),
                ("author_username", models.CharField(max_length=150)),
                ("campus_id", models.IntegerField(blank=True, null=True)),
                ("campus_name", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(choices=[("irc", "IRC"), ("campus-life", "Campus Life"), ("experiences", "Experiences"), ("academics", "Academics"), ("howto", "How-To")], max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=600, unique=True)),
                ("excerpt", models.TextField(max_length=1000)),
                ("body", models.TextField()),
                ("cover_image", models.URLField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("pending_review", "Pending Review"), ("published", "Published"), ("rejected", "Rejected")], default="pending_review", max_length=20)),
                ("featured", models.BooleanField(default=False)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("is_global_guide", models.BooleanField(default=False)),
                ("topic", models.CharField(blank=True, choices=[("Placements", "Placements"), ("Open Source", "Open Source"), ("Internships", "Internships"), ("Competitive Programming", "Competitive Programming"), ("GSoC", "GSoC"), ("Skills", "Skills")], max_length=50)),
                ("club_id", models.IntegerField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_by_id", models.CharField(blank=True, max_length=36)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "app_label": "articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status", "campus_id"], name="articles_art_status_8a0b0d_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status", "is_global_guide"], name="articles_art_status_2b0c1e_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status", "category"], name="articles_art_status_3c1d2f_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["author_id"], name="articles_art_author__4d2e3g_idx"),
        ),
        migrations.CreateModel(
            name="ArticleHelpful",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="helpful_votes", to="articles.article")),
            ],
            options={
                "app_label": "articles",
            },
        ),
        migrations.AddConstraint(
            model_name="articlehelpful",
            constraint=models.UniqueConstraint(fields=("article", "user_id"), name="articles_articlehelpful_unique"),
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_id", models.CharField(max_length=36)),
                ("author_username", models.CharField(max_length=150)),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="articles.article")),
            ],
            options={
                "app_label": "articles",
                "ordering": ["created_at"],
            },
        ),
    ]
