# Generated by Django 5.2.11 on 2026-03-05 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def null_empty_fk_strings(apps, schema_editor):
    """Convert empty string and invalid refs to NULL for author_id and reviewed_by_id before converting to FK."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Empty string -> NULL
        cursor.execute("UPDATE articles_article SET author_id = NULL WHERE author_id = ''")
        cursor.execute("UPDATE articles_article SET reviewed_by_id = NULL WHERE reviewed_by_id = ''")
        # Orphaned refs (user no longer exists) -> NULL so FK constraint can be applied
        cursor.execute(
            "UPDATE articles_article SET author_id = NULL WHERE author_id IS NOT NULL AND author_id NOT IN (SELECT id FROM accounts_user)"
        )
        cursor.execute(
            "UPDATE articles_article SET reviewed_by_id = NULL WHERE reviewed_by_id IS NOT NULL AND reviewed_by_id NOT IN (SELECT id FROM accounts_user)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_seed_subcategories'),
        ('campuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Allow NULL so we can convert empty strings before converting to FK
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='reviewed_by_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.RunPython(null_empty_fk_strings, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='articles_subcategory_category_slug_uniq',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_ar_status_5e66ee_idx',
            old_name='articles_art_status_8a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_ar_status_2a7223_idx',
            old_name='articles_art_status_2b0c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_ar_status_52a846_idx',
            old_name='articles_art_status_3c1d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_ar_author__8895b2_idx',
            old_name='articles_art_author__4d2e3g_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='campus_id',
            field=models.ForeignKey(blank=True, db_column='campus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='campuses.campus'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('onboarding-kit', 'The Onboarding Kit'), ('survival-food', 'Survival & Food'), ('club-directory', 'The Club Directory'), ('career-wins', 'Career & Wins'), ('local-travel', 'Local Travel & Hangout Spots'), ('amenities', 'Amenities')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='reviewed_by_id',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
    ]
