# Generated by Django 5.2.11 on 2026-03-05 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_subcategory_articles_subcategory_category_slug_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
        migrations.DeleteModel(
            name='ArticleHelpful',
        ),
        migrations.RemoveField(
            model_name='article',
            name='helpful_count',
        ),
        migrations.AddField(
            model_name='article',
            name='upvote_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ArticleSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('missing_info', 'Missing Info'), ('outdated_content', 'Outdated Content'), ('wrong_info', 'Wrong Info'), ('add_club_or_facility', 'Add a Club or Facility'), ('other', 'Other')], db_index=True, max_length=32)),
                ('content', models.CharField(max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='articles.article')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles_articlesuggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleUpvote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='articles.article')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='article_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles_articleupvote',
            },
        ),
        migrations.AddIndex(
            model_name='articlesuggestion',
            index=models.Index(fields=['article'], name='articles_sugg_article_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesuggestion',
            index=models.Index(fields=['reviewed', 'created_at'], name='articles_sugg_rev_created_idx'),
        ),
        migrations.AddIndex(
            model_name='articleupvote',
            index=models.Index(fields=['article', 'user'], name='articles_upv_article_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleupvote',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='articles_articleupvote_article_user_uniq'),
        ),
    ]
