# Generated by Django 5.2.11 on 2026-03-17 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_articleupvote_articlesuggestion_fk_to_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_confident_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(db_column='id_new', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(db_column='id_new', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(db_column='id_new', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
