# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0030_remove_article_club_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_keywords",
            field=models.JSONField(blank=True, default=list, help_text="SEO keywords list"),
        ),
    ]
