# Generated by Django 5.2.11 on 2026-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_article_meta_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'campus', 'display_order', 'slug'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
