# Generated by Django 5.2.11 on 2026-03-17 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_campus_uuid_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.UUIDField(db_column='id_new', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
