# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campuses", "0005_alter_campus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="campus",
            name="google_map_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
