# Generated by Django 5.2.11 on 2026-02-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_add_search_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='community_post_search_vector_idx',
        ),
        migrations.RenameIndex(
            model_name='postvote',
            new_name='community_p_post_id_7994a6_idx',
            old_name='community_p_post_id_idx',
        ),
        migrations.RenameIndex(
            model_name='postvote',
            new_name='community_p_post_id_59d987_idx',
            old_name='community_p_post_val_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
