# Generated by Django 6.0.2 on 2026-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Mobile number (e.g. E.164). Must be verified via OTP.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True after successful phone OTP verification.'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_verified'], name='accounts_us_phone_v_f7ff44_idx'),
        ),
    ]
