# Generated by Django 5.2.11 on 2026-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('senior', 'Senior'), ('admin', 'Admin')], db_index=True, default='student', help_text='User role; seniors can be verified separately.', max_length=20),
        ),
    ]
