# Generated by Django 5.2.11 on 2026-03-05 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_founding_editor_profile_campus_name'),
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.AlterField(
            model_name='foundingeditorprofile',
            name='campus_id',
            field=models.ForeignKey(blank=True, db_column='campus_id', help_text='Default campus for articles; matches campus list in frontend.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founding_editors', to='campuses.campus'),
        ),
        migrations.AlterField(
            model_name='foundingeditorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='founding_editor_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('senior', 'Senior'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('founding_editor', 'Founding Editor')], db_index=True, default='student', help_text='User role; seniors can be verified separately.', max_length=20),
        ),
    ]
