# Generated by Django 5.2.11 on 2026-04-02 08:14

from django.db import migrations, models


def normalize_user_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(role="student").update(role="intermediate_student")
    User.objects.filter(role="senior", is_verified_senior=True).update(role="founding_editor")
    User.objects.filter(role="senior", is_verified_senior=False).update(role="niat_student")
    User.objects.exclude(
        role__in=[
            "intermediate_student",
            "niat_student",
            "founding_editor",
            "moderator",
            "admin",
        ]
    ).update(role="intermediate_student")


def reverse_normalize_user_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(role="intermediate_student").update(role="student")
    User.objects.filter(role="niat_student").update(role="senior")
    User.objects.filter(role="founding_editor", is_verified_senior=True).update(role="senior")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_founding_editor_profile_campus_fk_to_pk'),
    ]

    operations = [
        migrations.RunPython(normalize_user_roles, reverse_normalize_user_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intermediate_student', 'Intermediate Student'), ('niat_student', 'NIAT Student'), ('founding_editor', 'Founding Editor'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='intermediate_student', help_text='User role in the canonical RBAC model.', max_length=20),
        ),
    ]
