# Generated by Django 5.2.11 on 2026-04-02 08:27

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(is_verified=True)


def mark_existing_users_unverified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(is_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, help_text="One-time token used to verify the user's email address.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="True once the user's email has been verified."),
        ),
        migrations.RunPython(mark_existing_users_verified, mark_existing_users_unverified),
    ]
