from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_email_verification_token_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text="True once the user completes onboarding.",
            ),
        ),
    ]

# Generated by Django 5.2.11 on 2026-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_email_verification_token_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the user completes onboarding.'),
        ),
    ]
