# Generated by Django 5.2.11 on 2026-02-17 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('body', models.TextField(blank=True)),
                ('is_answered', models.BooleanField(db_index=True, default=False)),
                ('upvote_count', models.IntegerField(db_index=True, default=0)),
                ('downvote_count', models.IntegerField(db_index=True, default=0)),
                ('view_count', models.IntegerField(db_index=True, default=0)),
                ('is_faq', models.BooleanField(db_index=True, default=False)),
                ('faq_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('upvote_count', models.IntegerField(db_index=True, default=0)),
                ('downvote_count', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='qa.question')),
            ],
            options={
                'db_table': 'qa_answer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(db_index=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qa.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_question_vote',
            },
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(db_index=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qa.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_answer_vote',
                'constraints': [models.UniqueConstraint(fields=('answer', 'user'), name='qa_answer_vote_unique'), models.CheckConstraint(condition=models.Q(('value__in', (1, -1))), name='qa_answer_vote_value_check')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_faq', 'faq_order'], name='qa_question_is_faq_eaf622_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionvote',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='qa_question_vote_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', (1, -1))), name='qa_question_vote_value_check'),
        ),
    ]
