# Generated by Django 5.2.11 on 2026-02-18 10:04
# Fixed: RenameIndex applied to state only so we don't DROP a missing index (qa_followup_questio_idx).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0005_fts5_question_search"),
    ]

    operations = [
        # Update migration state only; do not run DROP/CREATE index in DB (index may have different name in SQLite).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="followup",
                    new_name="qa_followup_questio_326938_idx",
                    old_name="qa_followup_questio_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="followup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
