# Generated by Django 5.2.11 on 2026-03-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_followup_answer_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followup',
            new_name='qa_followup_answer__7340cc_idx',
            old_name='qa_followup_answer__created_idx',
        ),
    ]
