# Generated by Django 5.2.11 on 2026-03-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_senioronboardingreview_linkedin_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senioronboardingreview',
            name='linkedin_profile_url',
            field=models.URLField(help_text='LinkedIn profile URL (e.g. https://linkedin.com/in/username)', max_length=512),
        ),
    ]
