# Generated by Django 6.0.2 on 2026-02-10 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('featured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('featured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts_set', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='community.post')),
            ],
            options={
                'verbose_name': 'Featured post',
                'verbose_name_plural': 'Featured posts',
                'db_table': 'moderation_featured_post',
                'ordering': ['order', '-featured_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingApprovalQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_queue_assignments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_queue_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending approval',
                'verbose_name_plural': 'Pending approvals',
                'db_table': 'moderation_pending_approval_queue',
                'indexes': [models.Index(fields=['status', 'content_type'], name='moderation__status_774aa3_idx'), models.Index(fields=['-created_at'], name='moderation__created_95d9ed_idx')],
            },
        ),
    ]
