# Generated by Django 6.0.2 on 2026-02-10 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('object_id', models.UUIDField(db_index=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement log',
                'verbose_name_plural': 'Engagement logs',
                'db_table': 'activity_engagement_log',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'action'], name='activity_en_content_2ebd07_idx'), models.Index(fields=['-created_at'], name='activity_en_created_101aba_idx')],
            },
        ),
    ]
